### ISSUE TITLE
Adding openings from existing projects

### ISSUE THREAD

**Issue by MaSchwarz** [Clariity/ChessOpenings#12]
**Is your feature request related to a problem? Please describe.**
I wouldn't really call it a "problem", but currently a downside to the project is the lack of openings.
There is a mechanism (e.g. using the contribution form) to add openings, but it heavily relies on the other peoples willingness to contributing to the project.

**Describe the solution you'd like**
Importing premade lists from other projects could be a solution.
(e.g. https://github.com/lichess-org/chess-openings or https://github.com/hayatbiralem/eco.json/blob/master/eco.json)

**Comment by Clariity** [comment]
A great source of openings, although more extensive and overlapping than desired for this site, perhaps something we can extend to in the future

I have plans to add an openings explorer similar to that of Lichess or Chess.com so it will come in handy, thank you
